### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [mpdroid/bones#2]
Hi, 
Can you please help me fix this issue?

[ 85%] Linking CXX executable ../../bin/bones
../extern/imgui/libimgui.a(gl3w.c.o): In function `get_proc':
gl3w.c:(.text+0x49): undefined reference to `glXGetProcAddress'
collect2: error: ld returned 1 exit status
products/bones/CMakeFiles/bones.dir/build.make:307: recipe for target 'bin/bones' failed
make[2]: *** [bin/bones] Error 1
CMakeFiles/Makefile2:359: recipe for target 'products/bones/CMakeFiles/bones.dir/all' failed
make[1]: *** [products/bones/CMakeFiles/bones.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I have checked the error in the other forums, and repos but I cannot fix this. 
Thanks

**Comment by mpdroid** [comment]
Hard to respond without knowing your OS and version. Try building [Azure Kinect Samples](https://github.com/microsoft/Azure-Kinect-Samples) and [ImGui](https://github.com/ocornut/imgui) standalone first.

**Comment by AswinkarthikeyenAK** [comment]
Sorry about that.
I am using Ubuntu 18.04.

I have installed Azure Kinect Samples. I will try to install ImGui now.

This is the error message I have after `ninja`


`[1/1] Linking CXX executable bin/bones
FAILED: bin/bones 
: && /usr/bin/c++    -Wl,--as-needed,-rpath-link=/home/aswink/bones_body_tracking/bones/build/bin products/bones/CMakeFiles/bones.dir/main.cpp.o products/bones/CMakeFiles/bones.dir/texture.cpp.o products/bones/CMakeFiles/bones.dir/clusterizer.cpp.o products/bones/CMakeFiles/bones.dir/viewerwindow.cpp.o products/bones/CMakeFiles/bones.dir/renderor.cpp.o products/bones/CMakeFiles/bones.dir/azure_vision_request.cpp.o products/bones/CMakeFiles/bones.dir/euclid.cpp.o products/bones/CMakeFiles/bones.dir/controller.cpp.o products/bones/CMakeFiles/bones.dir/kinector.cpp.o products/bones/CMakeFiles/bones.dir/scene/scene.cpp.o products/bones/CMakeFiles/bones.dir/scene/writair.cpp.o products/bones/CMakeFiles/bones.dir/scene/thingfinder.cpp.o  -o bin/bones  -Wl,-rpath,"\$ORIGIN:/usr/local/lib"  /usr/lib/libk4abt.so.1.0.0  products/extern/glfw/src/src/libglfw3.a  products/extern/imgui/libimgui.a  /usr/local/lib/libcpprest.so.2.10  products/extern/cilantro/libcilantro.a  /usr/lib/x86_64-linux-gnu/libopencv_shape.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_stitching.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_superres.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_videostab.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_aruco.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_bgsegm.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_bioinspired.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_ccalib.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_datasets.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_dpm.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_face.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_freetype.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_fuzzy.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_hdf.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_line_descriptor.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_optflow.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_plot.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_reg.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_saliency.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_stereo.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_structured_light.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_surface_matching.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_text.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_ximgproc.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_xobjdetect.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_xphoto.so.3.2.0  /usr/lib/x86_64-linux-gnu/libk4a.so.1.3.0  -latomic  -lstdc++fs  /usr/lib/x86_64-linux-gnu/librt.so  -lm  -ldl  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXrandr.so  /usr/lib/x86_64-linux-gnu/libXinerama.so  /usr/lib/x86_64-linux-gnu/libXxf86vm.so  /usr/lib/x86_64-linux-gnu/libXcursor.so  -lpthread  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so  -lpthread  /usr/lib/x86_64-linux-gnu/libopencv_video.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_viz.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_phase_unwrapping.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_rgbd.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_features2d.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_flann.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_ml.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_photo.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.3.2.0  /usr/lib/x86_64-linux-gnu/libopencv_core.so.3.2.0 && :
/usr/bin/ld: products/bones/CMakeFiles/bones.dir/main.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed`




Thanks

**Comment by mpdroid** [comment]
if you are able to build and run Azure Kinect Samples, then ImGui also should be ok. The error seems to indicate problem with boost dependency required by cpprestsdk. You could try some of the suggestions on https://github.com/microsoft/cpprestsdk/issues/792

**Comment by AswinkarthikeyenAK** [comment]
Hi, 

The build fails when creating a executable in bin/bones 
`[80/80] Linking CXX executable bin/bones
FAILED: bin/bones 
`

`/usr/bin/ld: products/bones/CMakeFiles/bones.dir/main.cpp.o: undefined reference to symbol 'CONF_modules_unload@@OPENSSL_1_1_0'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed
`
This is the error i have now, where I've made changes that were mentioned in the [https://github.com/microsoft/cpprestsdk/issues/1388](url)

I can run the simple_3d_viewer and visualize the data.
Maybe its the issue with the other files, Ill update here once I find the fix so it will be helpful for others using this package if needed.
Thanks for your time

**Comment by mpdroid** [comment]
good you are making progress. looks like openssl library is missing - https://help.ubuntu.com/community/OpenSSL

**Comment by AswinkarthikeyenAK** [comment]
Hi, 
Its been a while since I tried to fix the issues I was facing. Unfortunately, I am not able to fix it. 

`[100%] Linking CXX executable ../../bin/bones
/usr/bin/ld: CMakeFiles/bones.dir/main.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
products/bones/CMakeFiles/bones.dir/build.make:306: recipe for target 'bin/bones' failed
make[2]: *** [bin/bones] Error 1
CMakeFiles/Makefile2:359: recipe for target 'products/bones/CMakeFiles/bones.dir/all' failed
make[1]: *** [products/bones/CMakeFiles/bones.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
` 
I have tried most of the solution that I found online regarding this error, but I couldn't fix it. Any assistance to fix this would be really helpful

**Comment by tynguyen** [comment]
I also encountered this problem. A simple fix is to install the library and link to it by putting a line into the CMakeLists.txt file 
For example, with the error
`/usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status`
Install libboost_system and then add the following line: 
`link_libraries(-lboost_system)`
